### ISSUE TITLE
goodreads downloading fails

### ISSUE THREAD

**Issue by monkey0head** [Darel13712/rs_datasets#10]
![image](https://user-images.githubusercontent.com/44523356/141439818-b07051d2-26f1-4d9e-a405-3af294a85578.png)

**Comment by Darel13712** [comment]
Similar to #8 , this is caused by Google Drive blocking the attempt to download the file. The only solution for now is to download it manually =(
Other option is to move it somewhere else, I contacted the author but he didn't respond.
