### ISSUE TITLE
Dating Agency dataset not available

### ISSUE THREAD

**Issue by inpefess** [Darel13712/rs_datasets#11]
```shell
rs_datasets.DatingAgency()
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
The site went down: http://www.occamslab.com/petricek/data/ responds with a domain selling ad

**Comment by Darel13712** [comment]
I wasn't able to find it anywhere else, and I do not have a downloaded version, so it seems this dataset is lost. I deleted it with version `0.5.0`
