### ISSUE TITLE
Unable to download datasets - access to download link denied

### ISSUE THREAD

**Issue by anubane** [Darel13712/rs_datasets#8]
Upon using the code:
```python
from rs_datasets import Diginetica
d = Diginetica('~/datasets/diginetica')
d.info()
```
I am receiving the following error message:
```bash
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
```

**Comment by Darel13712** [comment]
I was able to reproduce this issue. 

It seems that this is a problem with google drive blocking download for public files via command line, I found an issue on a gdown repo https://github.com/wkentaro/gdown/issues/43

It seems that the only workaround at this moment would be to manually replicate steps from the `_download` [method](https://github.com/Darel13712/rs_datasets/blob/6530da5136063cecc15207745e27710280f6bd6f/rs_datasets/diginetica.py#L52). 

So what you have to do is:
- download dataset using your browser from https://drive.google.com/uc?id=0B7XZSACQf0KdenRmMk8yVUU5LWc
- place it in where it should have been downloaded, which in your case would be `~/datasets/diginetica/diginetica.zip`
- call `rs_datasets.data_loader.extract` on this archive or do the same actions yourself
- remove `diginetica.zip` file

Now you should be able to load it with `d = Diginetica('~/datasets/diginetica')`.

Hope this helps and sorry for the inconvenience.
