### ISSUE TITLE
lastfm read fails

### ISSUE THREAD

**Issue by monkey0head** [Darel13712/rs_datasets#9]
<img width="839" alt="Screenshot 2021-11-12 at 11 48 43" src="https://user-images.githubusercontent.com/44523356/141439371-ec764082-c650-4bbb-b05b-d860a211849c.png">

**Comment by Darel13712** [comment]
This problem occurs with `datatable==1.0.0` the solution is to either downgrade to `0.11.1` or wait for a new release. There is a dev build, but I guess it's safer to downgrade.
